-- 1. Buat tabel rfid_cards jika belum ada
CREATE TABLE IF NOT EXISTS public.rfid_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_member_id BIGINT NOT NULL,
    card_number TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Pastikan foreign key relationship ada
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_name = 'rfid_cards_organization_member_id_fkey'
        AND table_name = 'rfid_cards'
    ) THEN
        ALTER TABLE public.rfid_cards
        ADD CONSTRAINT rfid_cards_organization_member_id_fkey
        FOREIGN KEY (organization_member_id)
        REFERENCES public.organization_members(id)
        ON DELETE CASCADE;
    END IF;
END $$;

-- 3. Buat RLS (Row Level Security) Policies
ALTER TABLE public.rfid_cards ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.rfid_cards;
    DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON public.rfid_cards;
    DROP POLICY IF EXISTS "Enable update access for authenticated users" ON public.rfid_cards;
EXCEPTION WHEN OTHERS THEN
END $$;

CREATE POLICY "Enable read access for authenticated users" 
ON public.rfid_cards FOR SELECT 
TO authenticated USING (true);

CREATE POLICY "Enable insert access for authenticated users" 
ON public.rfid_cards FOR INSERT 
TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update access for authenticated users" 
ON public.rfid_cards FOR UPDATE 
TO authenticated USING (true) WITH CHECK (true);

-- 4. Reload schema cache untuk PostgREST
NOTIFY pgrst, 'reload schema';
