// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/karyawan_wajah.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 644565229026393901),
    name: 'KaryawanWajah',
    lastPropertyId: const obx_int.IdUid(8, 3152709666438246567),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8626836867565474678),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7607069420853143171),
        name: 'organizationMemberId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 1789938161532769008),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3903796708229298584),
        name: 'organizationId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 2187596769051640052),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7111167614179314663),
        name: 'namaLengkap',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1526020971928562352),
        name: 'profilePhotoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6142035961070109803),
        name: 'faceEmbedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(3, 7295842027488810617),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4755862382913610031),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3152709666438246567),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 644565229026393901),
    lastIndexId: const obx_int.IdUid(3, 7295842027488810617),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    KaryawanWajah: obx_int.EntityDefinition<KaryawanWajah>(
      model: _entities[0],
      toOneRelations: (KaryawanWajah object) => [],
      toManyRelations: (KaryawanWajah object) => {},
      getId: (KaryawanWajah object) => object.id,
      setId: (KaryawanWajah object, int id) {
        object.id = id;
      },
      objectToFB: (KaryawanWajah object, fb.Builder fbb) {
        final namaLengkapOffset = fbb.writeString(object.namaLengkap);
        final profilePhotoUrlOffset = object.profilePhotoUrl == null
            ? null
            : fbb.writeString(object.profilePhotoUrl!);
        final faceEmbeddingOffset = object.faceEmbedding == null
            ? null
            : fbb.writeListFloat32(object.faceEmbedding!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.organizationMemberId);
        fbb.addInt64(2, object.organizationId);
        fbb.addOffset(3, namaLengkapOffset);
        fbb.addOffset(4, profilePhotoUrlOffset);
        fbb.addOffset(5, faceEmbeddingOffset);
        fbb.addInt64(6, object.lastSyncedAt?.millisecondsSinceEpoch);
        fbb.addBool(7, object.isActive);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSyncedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final organizationMemberIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final organizationIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final namaLengkapParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final profilePhotoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final faceEmbeddingParam = const obx_int.Float32ListReader()
            .vTableGetNullable(buffer, rootOffset, 14);
        final lastSyncedAtParam = lastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedAtValue);
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = KaryawanWajah(
          id: idParam,
          organizationMemberId: organizationMemberIdParam,
          organizationId: organizationIdParam,
          namaLengkap: namaLengkapParam,
          profilePhotoUrl: profilePhotoUrlParam,
          faceEmbedding: faceEmbeddingParam,
          lastSyncedAt: lastSyncedAtParam,
          isActive: isActiveParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [KaryawanWajah] entity fields to define ObjectBox queries.
class KaryawanWajah_ {
  /// See [KaryawanWajah.id].
  static final id = obx.QueryIntegerProperty<KaryawanWajah>(
    _entities[0].properties[0],
  );

  /// See [KaryawanWajah.organizationMemberId].
  static final organizationMemberId = obx.QueryIntegerProperty<KaryawanWajah>(
    _entities[0].properties[1],
  );

  /// See [KaryawanWajah.organizationId].
  static final organizationId = obx.QueryIntegerProperty<KaryawanWajah>(
    _entities[0].properties[2],
  );

  /// See [KaryawanWajah.namaLengkap].
  static final namaLengkap = obx.QueryStringProperty<KaryawanWajah>(
    _entities[0].properties[3],
  );

  /// See [KaryawanWajah.profilePhotoUrl].
  static final profilePhotoUrl = obx.QueryStringProperty<KaryawanWajah>(
    _entities[0].properties[4],
  );

  /// See [KaryawanWajah.faceEmbedding].
  static final faceEmbedding = obx.QueryHnswProperty<KaryawanWajah>(
    _entities[0].properties[5],
  );

  /// See [KaryawanWajah.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<KaryawanWajah>(
    _entities[0].properties[6],
  );

  /// See [KaryawanWajah.isActive].
  static final isActive = obx.QueryBooleanProperty<KaryawanWajah>(
    _entities[0].properties[7],
  );
}
