-- Create departments table
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Drop existing constraints if they exist
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'fk_departments_organization'
    ) THEN
        ALTER TABLE public.departments DROP CONSTRAINT fk_departments_organization;
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'uk_departments_name_organization'
    ) THEN
        ALTER TABLE public.departments DROP CONSTRAINT uk_departments_name_organization;
    END IF;
END $$;

-- Add foreign key constraint to organizations table
ALTER TABLE public.departments
ADD CONSTRAINT fk_departments_organization
FOREIGN KEY (organization_id)
REFERENCES public.organizations(id)
ON DELETE CASCADE;

-- Add unique constraint for department name per organization
ALTER TABLE public.departments
ADD CONSTRAINT uk_departments_name_organization
UNIQUE (name, organization_id);

-- Create index on organization_id for faster queries
CREATE INDEX IF NOT EXISTS idx_departments_organization_id
ON public.departments(organization_id);

-- Create index on name for faster search
CREATE INDEX IF NOT EXISTS idx_departments_name
ON public.departments(name);

-- Enable Row Level Security
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Organization members can view departments" ON public.departments;
DROP POLICY IF EXISTS "Organization admins can insert departments" ON public.departments;
DROP POLICY IF EXISTS "Organization admins can update departments" ON public.departments;
DROP POLICY IF EXISTS "Organization admins can delete departments" ON public.departments;

-- Create policy to allow organization members to read departments
CREATE POLICY "Organization members can view departments"
ON public.departments FOR SELECT
USING (
    organization_id IN (
        SELECT organization_id 
        FROM public.organization_members 
        WHERE user_id = auth.uid() AND is_active = true
    )
);

-- Create policy to allow organization admins to insert departments
CREATE POLICY "Organization admins can insert departments"
ON public.departments FOR INSERT
WITH CHECK (
    organization_id IN (
        SELECT organization_id 
        FROM public.organization_members 
        WHERE user_id = auth.uid() AND role_id IN (1, 2) AND is_active = true
    )
);

-- Create policy to allow organization admins to update departments
CREATE POLICY "Organization admins can update departments"
ON public.departments FOR UPDATE
USING (
    organization_id IN (
        SELECT organization_id 
        FROM public.organization_members 
        WHERE user_id = auth.uid() AND role_id IN (1, 2) AND is_active = true
    )
);

-- Create policy to allow organization admins to delete departments
CREATE POLICY "Organization admins can delete departments"
ON public.departments FOR DELETE
USING (
    organization_id IN (
        SELECT organization_id 
        FROM public.organization_members 
        WHERE user_id = auth.uid() AND role_id IN (1, 2) AND is_active = true
    )
);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS update_departments_updated_at ON public.departments;

CREATE TRIGGER update_departments_updated_at
    BEFORE UPDATE ON public.departments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
